universe = vanilla
executable = run_source_rescue_job.sh
arguments = $(JOB_ID) 100000

initialdir = /uscms/homes/s/sergo/g4beamline/cooling_demonstrator/target-transfer-stitched/condor/option_b/source_z2000

output = logs/rescue_job_$(JOB_ID).out
error = logs/rescue_job_$(JOB_ID).err
log = logs/rescue_condor.log

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = inputs, summarize_source_job.py
transfer_output_files = rescue_job_$(JOB_ID)

request_cpus = 1
request_memory = 4 GB
request_disk = 8 GB

+JobFlavour = "workday"

queue JOB_ID from (
1
5
7
8
)
