universe = vanilla
executable = /uscms/homes/s/sergo/g4beamline/cooling_demonstrator/target-transfer-stitched/condor/option_b/nominal_pi10M/run_nominal_pi10M_job.sh
arguments = $(Process) 1000000 3400000

initialdir = /uscms/homes/s/sergo/g4beamline/cooling_demonstrator/target-transfer-stitched/condor/option_b/nominal_pi10M

output = logs/job_$(Process).out
error = logs/job_$(Process).err
log = logs/condor.log

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = inputs, make_resampled_beam.py, summarize_nominal_job.py, source_z2000_pi_mu.csv
transfer_output_files = job_$(Process)

request_cpus = 1
request_memory = 4 GB
request_disk = 6 GB

+JobFlavour = "workday"

queue 10
