universe = vanilla
executable = run_chicane_triplet_job.sh
arguments = $(point_id) $(group_name) $(g12_scale) $(g345_scale) $(g678_scale) $(n_events) pi+ 2000000 $(Cluster)

initialdir = /uscms/homes/s/sergo/g4beamline/cooling_demonstrator/target-transfer-stitched/condor/chicane_group_scan

output = logs/triplet_$(Cluster)_point_$(point_id).out
error = logs/triplet_$(Cluster)_point_$(point_id).err
log = logs/triplet_condor.log

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = inputs, make_resampled_beam.py, scale_chicane_triplet.py, summarize_chicane_group_job.py, ../source_z2000/combined/source_z2000_pi_mu.csv
transfer_output_files = jobs/$(Cluster)_point_$(point_id)

request_cpus = 1
request_memory = 2 GB
request_disk = 4 GB

+JobFlavour = "workday"

queue point_id,group_name,g12_scale,g345_scale,g678_scale,n_events from triplet_scout_points.txt
