universe = vanilla
executable = run_chicane_triplet_job.sh
arguments = 190$(Process) G12_G345_G678 0.95 1.15 1.25 1000000 pi+ 2800000 $(Cluster)

initialdir = /uscms/homes/s/sergo/g4beamline/cooling_demonstrator/target-transfer-stitched/condor/chicane_group_scan

output = logs/triplet_highstat_best_$(Cluster)_$(Process).out
error = logs/triplet_highstat_best_$(Cluster)_$(Process).err
log = logs/triplet_highstat_best_condor.log

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = inputs, make_resampled_beam.py, scale_chicane_triplet.py, summarize_chicane_group_job.py, ../source_z2000/combined/source_z2000_pi_mu.csv
transfer_output_files = jobs/$(Cluster)_point_190$(Process)

request_cpus = 1
request_memory = 2 GB
request_disk = 4 GB

+JobFlavour = "workday"

queue 100
