universe = vanilla
executable = run_chicane_location_job.sh
arguments = 240$(Process) G12_G345_G678_Z345_Z678 0.95 1.15 1.25 200 -400 1000000 pi+ 3800000 $(Cluster)

initialdir = /uscms/homes/s/sergo/g4beamline/cooling_demonstrator/target-transfer-stitched/condor/chicane_group_scan

output = logs/chicane_location_best_$(Cluster)_$(Process).out
error = logs/chicane_location_best_$(Cluster)_$(Process).err
log = logs/chicane_location_best_condor.log

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = inputs, make_resampled_beam.py, scale_chicane_location.py, summarize_chicane_group_job.py, ../source_z2000/combined/source_z2000_pi_mu.csv
transfer_output_files = jobs/$(Cluster)_point_240$(Process)

request_cpus = 1
request_memory = 2 GB
request_disk = 4 GB

+JobFlavour = "workday"

queue 100
