universe = vanilla
executable = run_rescue_job.sh
arguments = $(jobid) 10000

initialdir = /uscms/homes/s/sergo/g4beamline/cooling_demonstrator/target-transfer-stitched/condor

output = logs/rescue_$(jobid).out
error = logs/rescue_$(jobid).err
log = logs/rescue_condor.log

should_transfer_files = NO

request_cpus = 1
request_memory = 2 GB
request_disk = 4 GB

+JobFlavour = "workday"

queue jobid from (
1
2
3
4
7
11
12
19
)
