universe = vanilla
executable = run_scan_job.sh
arguments = $(point_id) $(qf_gradient) $(qd_gradient) 100000

initialdir = /uscms/homes/s/sergo/g4beamline/cooling_demonstrator/target-transfer-stitched/condor/quad_gradient_scan

output = logs/point_$(point_id).out
error = logs/point_$(point_id).err
log = logs/condor.log

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = inputs, summarize_job.py
transfer_output_files = jobs/point_$(point_id)

request_cpus = 1
request_memory = 2 GB
request_disk = 4 GB

+JobFlavour = "workday"

queue point_id,qf_gradient,qd_gradient from scan_points.txt
